/**
 * @mnemonik-xyz/conformance
 *
 * A2A protocol conformance test vectors for the Mnemonic attestation pipeline.
 *
 * Each vector encodes:
 *  - the A2A object as regular JSON (documentation only),
 *  - the RFC 8785 JCS canonical bytes as hex,
 *  - the CBOR envelope hex (equal to JCS bytes in V1 — the inner payload is the JCS bytes verbatim),
 *  - the COSE_Sign1 envelope as hex,
 *  - the 64-byte Ed25519 keypair secret (fixed test seed, never use in production).
 *
 * All vectors are generated by `core/tests/a2a_golden_fixtures.rs` with a fixed
 * deterministic seed (see that file for the seed hex and determinism contract).
 *
 * @see work/a2a-bridge/tech-spec.md Decision 1 (dual canonicalization)
 * @see .claude/skills/project-knowledge/references/conformance.md
 */

import vectors from "../vectors-a2a-v1.0.0.json" assert { type: "json" };

export { vectors };

/** One A2A conformance vector entry. */
export interface A2aVector {
  /** Stable, human-readable test-case label. */
  name: string;
  /** The A2A object serialised as regular JSON (not JCS). Documentation only. */
  a2a_json: string;
  /**
   * Hex of the RFC 8785 JCS canonical bytes (`to_jcs_bytes()`).
   * This is the authoritative byte sequence for conformance: third-party
   * implementations must produce the exact same hex for the object in `a2a_json`.
   */
  jcs_canonical_hex: string;
  /**
   * Hex of the CBOR envelope wrapping the JCS bytes.
   * In V1 the inner payload is the JCS bytes verbatim (Decision 1:
   * do not re-canonicalize). Therefore `cbor_envelope_hex == jcs_canonical_hex`.
   */
  cbor_envelope_hex: string;
  /**
   * Hex of the COSE_Sign1 envelope (`to_canonical_envelope()`).
   * Third-party implementations must produce the exact same bytes when signing
   * the JCS payload with the keypair specified in `keypair_secret_hex`.
   */
  cose_signed_hex: string;
  /**
   * Hex of the 64-byte Ed25519 keypair secret (seed + public key, as produced
   * by `Keypair::to_bytes()` in the solana-sdk). Deterministic across all entries.
   * TEST-ONLY — never use this key to sign real attestations.
   */
  keypair_secret_hex: string;
}

/** Load all vectors typed. */
export function loadVectors(): A2aVector[] {
  return vectors as A2aVector[];
}

/** Return vectors filtered by name prefix, useful in targeted conformance runs. */
export function vectorsForKind(kind: "message" | "task" | "artifact"): A2aVector[] {
  return loadVectors().filter((v) => v.name.startsWith(kind));
}
