//! Build-time projection of skill manifests into compile-time string constants.
//!
//! Reads every `*.md` file under `mcp/assets/skills/`, parses the H1 title +
//! `## Purpose` + `## Trigger` H2 sections, and emits a Rust module that
//! `include!()`-s into `mcp/src/mcp.rs`. Three slots per manifest:
//!
//!   - `FULL_MARKDOWN` — full file body (for `resources/read`, `prompts/get`).
//!   - `PURPOSE_PLUS_TRIGGER` — Purpose section + Trigger section concatenated
//!     with a blank line (for the enriched `tools/list` description in Task 2).
//!   - `PURPOSE_ONE_LINER` — just the Purpose section, trimmed (for short
//!     descriptions / overview).
//!
//! Each of these is required: the build fails with a named-file error if a
//! manifest is missing `## Purpose` or `## Trigger`. The seven-manifest
//! invariant (per user-spec AC1) is enforced by an EXPECTED set listed below;
//! a missing file fails the build with the offending name in the message.

use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::Path;

/// The seven manifests user-spec AC1 requires. Missing files OR extra files
/// fail the build with the offending name surfaced. Order is alphabetical for
/// determinism of the generated module.
const EXPECTED_MANIFESTS: &[&str] = &[
    "attest",
    "checkpoint",
    "help",
    "init",
    "recall",
    "status",
    "verify",
];

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR set by cargo");
    let skills_dir = Path::new(&manifest_dir).join("assets").join("skills");
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR set by cargo");
    let out_file = Path::new(&out_dir).join("skills_generated.rs");

    // Rerun if any manifest changes (path is relative to CARGO_MANIFEST_DIR).
    println!("cargo:rerun-if-changed=assets/skills");
    println!("cargo:rerun-if-changed=build.rs");

    if !skills_dir.is_dir() {
        panic!(
            "skill manifests directory missing: {}\n\
             expected layout: mcp/assets/skills/<name>.md for each of: {:?}",
            skills_dir.display(),
            EXPECTED_MANIFESTS
        );
    }

    // Collect manifests that physically exist on disk.
    let mut found: BTreeMap<String, String> = BTreeMap::new();
    for entry in fs::read_dir(&skills_dir).expect("read_dir on assets/skills") {
        let entry = entry.expect("dir entry");
        let path = entry.path();
        if !path.is_file() {
            continue;
        }
        if path.extension().and_then(|s| s.to_str()) != Some("md") {
            continue;
        }
        let stem = path
            .file_stem()
            .and_then(|s| s.to_str())
            .expect("manifest filename utf-8")
            .to_string();
        let body = fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("read manifest {}: {}", path.display(), e));
        found.insert(stem, body);
    }

    // Enforce the EXPECTED set exactly — no missing, no extras.
    for name in EXPECTED_MANIFESTS {
        if !found.contains_key(*name) {
            panic!(
                "missing required skill manifest: {}.md\n\
                 expected at: {}",
                name,
                skills_dir.join(format!("{name}.md")).display()
            );
        }
    }
    for name in found.keys() {
        if !EXPECTED_MANIFESTS.contains(&name.as_str()) {
            panic!(
                "unexpected skill manifest file: {}.md\n\
                 EXPECTED_MANIFESTS in mcp/build.rs needs updating, or remove the file",
                name
            );
        }
    }

    // Parse + emit.
    let mut emitted = String::new();
    emitted.push_str("// AUTO-GENERATED by mcp/build.rs — do not edit by hand.\n");
    emitted.push_str("// Source: mcp/assets/skills/*.md\n\n");
    emitted.push_str("pub struct SkillManifest {\n");
    emitted.push_str("    pub name: &'static str,\n");
    emitted.push_str("    pub full_markdown: &'static str,\n");
    emitted.push_str("    pub purpose_plus_trigger: &'static str,\n");
    emitted.push_str("    pub purpose_one_liner: &'static str,\n");
    emitted.push_str("}\n\n");

    let mut all_entries: Vec<String> = Vec::new();
    for name in EXPECTED_MANIFESTS {
        let body = found.get(*name).expect("checked above");
        let parsed = parse_manifest(name, body);
        let const_name = name.to_uppercase();
        emitted.push_str(&format!(
            "pub const SKILL_{const_name}_NAME: &str = {name_lit};\n",
            name_lit = rust_str_literal(&format!("mnemonik-{name}"))
        ));
        emitted.push_str(&format!(
            "pub const SKILL_{const_name}_FULL_MARKDOWN: &str = {lit};\n",
            lit = rust_str_literal(&parsed.full_markdown)
        ));
        emitted.push_str(&format!(
            "pub const SKILL_{const_name}_PURPOSE_PLUS_TRIGGER: &str = {lit};\n",
            lit = rust_str_literal(&parsed.purpose_plus_trigger)
        ));
        emitted.push_str(&format!(
            "pub const SKILL_{const_name}_PURPOSE_ONE_LINER: &str = {lit};\n\n",
            lit = rust_str_literal(&parsed.purpose_one_liner)
        ));

        all_entries.push(format!(
            "    SkillManifest {{\n\
             \x20       name: SKILL_{const_name}_NAME,\n\
             \x20       full_markdown: SKILL_{const_name}_FULL_MARKDOWN,\n\
             \x20       purpose_plus_trigger: SKILL_{const_name}_PURPOSE_PLUS_TRIGGER,\n\
             \x20       purpose_one_liner: SKILL_{const_name}_PURPOSE_ONE_LINER,\n\
             \x20   }},"
        ));
    }

    emitted.push_str(&format!(
        "pub const ALL_SKILLS: &[SkillManifest] = &[\n{}\n];\n",
        all_entries.join("\n")
    ));

    fs::write(&out_file, emitted).expect("write skills_generated.rs");
}

struct Parsed {
    full_markdown: String,
    purpose_plus_trigger: String,
    purpose_one_liner: String,
}

/// Parse a manifest's body. Surfaces both required H2 sections as separate
/// strings; panics with a named-file error if either is missing.
fn parse_manifest(name: &str, body: &str) -> Parsed {
    let purpose = extract_h2_section(body, "Purpose").unwrap_or_else(|| {
        panic!(
            "manifest {}.md missing required `## Purpose` H2 section",
            name
        )
    });
    let trigger = extract_h2_section(body, "Trigger").unwrap_or_else(|| {
        panic!(
            "manifest {}.md missing required `## Trigger` H2 section",
            name
        )
    });

    let purpose_trim = purpose.trim().to_string();
    let trigger_trim = trigger.trim().to_string();

    // Purpose+Trigger surface for tools/list descriptions.
    let purpose_plus_trigger = format!(
        "Purpose: {purpose}\n\nTrigger: {trigger}",
        purpose = purpose_trim,
        trigger = trigger_trim
    );

    // One-liner = first non-empty line of Purpose section.
    let purpose_one_liner = purpose_trim
        .lines()
        .find(|line| !line.trim().is_empty())
        .unwrap_or(&purpose_trim)
        .trim()
        .to_string();

    Parsed {
        full_markdown: body.to_string(),
        purpose_plus_trigger,
        purpose_one_liner,
    }
}

/// Extract the body of an H2 section with the given title. Returns the text
/// between the `## <title>` line (exclusive) and the next `## ` line (exclusive),
/// or None if the section header is not present. Whitespace-only sections
/// count as present (the caller's `.trim()` handles emptiness).
fn extract_h2_section(body: &str, title: &str) -> Option<String> {
    let header = format!("## {title}");
    let mut lines = body.lines().enumerate();
    let start = lines.find_map(|(i, l)| {
        // Match exact "## Title" with no trailing tokens — avoids matching
        // e.g. "## Purpose-driven" if someone writes such a heading.
        if l.trim() == header {
            Some(i + 1)
        } else {
            None
        }
    })?;

    let all_lines: Vec<&str> = body.lines().collect();
    let end = all_lines
        .iter()
        .enumerate()
        .skip(start)
        .find_map(|(i, l)| {
            if l.starts_with("## ") || l.starts_with("# ") {
                Some(i)
            } else {
                None
            }
        })
        .unwrap_or(all_lines.len());

    Some(all_lines[start..end].join("\n"))
}

/// Emit a Rust string literal that round-trips arbitrary UTF-8. Uses a raw
/// string with the minimum-`#` padding necessary to avoid clashes with the
/// content. Falls back to escaped form if the body contains an unmatched raw
/// terminator (unlikely in markdown).
fn rust_str_literal(s: &str) -> String {
    // Find the maximum run of `#` after `"` so we can outscope it.
    let mut hashes = 0usize;
    let bytes = s.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == b'"' {
            // Count following `#`s.
            let mut count = 0;
            let mut j = i + 1;
            while j < bytes.len() && bytes[j] == b'#' {
                count += 1;
                j += 1;
            }
            if count >= hashes {
                hashes = count + 1;
            }
            i = j;
        } else {
            i += 1;
        }
    }
    let pad = "#".repeat(hashes);
    format!("r{pad}\"{s}\"{pad}")
}
