// Byte-for-byte parity tests for the extension's WASM crypto pipeline
// against `core`'s native path. Inputs come from the golden fixture set
// at `tests/fixtures/golden/`, generated by:
//
//   cargo run -p mnemonic-core --features golden-fixtures \
//     --example emit_golden -- packages/extension/tests/fixtures/golden/
//
// Each `cose_sign1_seed_<N>.bin` / `compressed_emb_seed_<N>.bin` /
// `canonical_cbor_seed_<N>.bin` is an authoritative byte sequence the
// browser MUST reproduce — drift here means a memory signed in the
// extension would fail server-side `verify_artifact`.
//
// Loader: we bypass the production `cose.ts` dynamic-import path
// (`new URL("./wasm/mnemonic_core.js", import.meta.url)` resolves
// relative to the bundler-emitted location, which doesn't exist in the
// vitest realm). The `--target nodejs` artefact at
// `core/pkg-nodejs/` is loaded directly via `await import()` and then
// installed via `__setWasmForTesting`. Same approach the SDK takes for
// its `cose.golden.test.ts`.

import { describe, it, expect, beforeAll } from "vitest";
import { readFileSync } from "node:fs";
import { readFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import {
  __setWasmForTesting,
  blake3Hash,
  blake3HashHex,
  compressEmbedding,
  decompressEmbedding,
  signAttestationBundle,
  signCosePayload,
  toCanonicalCbor,
  type KeypairJson,
} from "../../../src/runtime/sign/cose.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, "../../../../..");
const FIXTURE_DIR = path.resolve(__dirname, "../../fixtures/golden");
// `--target web` artefact + bytes-via-fs: Node 22 + wasm-bindgen 0.2.100
// crashes inside `__wbindgen_init_externref_table` when the
// `--target nodejs` artefact's `WebAssembly.Table.grow(4)` runs (same
// reference-types init bug the SDK's `wasm.ts` documents). Loading the
// `--target web` artefact and passing bytes to `default()` avoids the
// CJS init path entirely.
const WEB_WASM_JS = path.join(REPO_ROOT, "core/pkg-web/mnemonic_core.js");
const WEB_WASM_BIN = path.join(REPO_ROOT, "core/pkg-web/mnemonic_core_bg.wasm");

interface ManifestEntry {
  seed: number;
  plaintext: string;
  signer_pubkey_b58: string;
  signer_secret_hex: string;
  embedding_f32: number[];
  dim: number;
  bit_width: number;
  content_hash_hex: string;
  canonical_cbor_b64: string;
  cose_sign1_b64: string;
  compressed_emb_b64: string;
}

let manifest: ManifestEntry[] = [];

beforeAll(async () => {
  const manifestPath = path.join(FIXTURE_DIR, "manifest.json");
  manifest = JSON.parse(readFileSync(manifestPath, "utf8")) as ManifestEntry[];
  expect(manifest.length).toBeGreaterThanOrEqual(5);
  // Self-shim: wasm-bindgen `getrandom`'s `js` feature probes
  // `self.crypto` first; in Node ESM `self` is undefined. Aliasing it
  // to `globalThis` lets the WebCrypto branch resolve. Idempotent and
  // scoped to test setup. (Same workaround the SDK's `wasm.ts`
  // applies at production runtime.)
  const gt = globalThis as { self?: unknown };
  if (typeof gt.self === "undefined") gt.self = globalThis;
  const wasm = (await import(
    /* @vite-ignore */ pathToFileURL(WEB_WASM_JS).href
  )) as {
    default: (input: { module_or_path: Uint8Array }) => Promise<unknown>;
  };
  const bytes = await readFile(WEB_WASM_BIN);
  await wasm.default({ module_or_path: bytes });
  __setWasmForTesting(wasm as never);
});

/** Build the `KeypairJson` shape the WASM expects from a 64-byte hex
 *  Solana secret. Mirrors what the webapp's localStorage round-trip
 *  produces. */
function keypairFromSecret(secretHex: string, pubkey: string): KeypairJson {
  const bytes = new Uint8Array(secretHex.length / 2);
  for (let i = 0; i < bytes.length; i++) {
    bytes[i] = parseInt(secretHex.slice(i * 2, i * 2 + 2), 16);
  }
  return { secret: Array.from(bytes), pubkey_base58: pubkey };
}

describe("WASM crypto pipeline parity (T05 golden fixtures)", () => {
  it("loads ≥5 fixtures from disk", () => {
    expect(manifest.length).toBeGreaterThanOrEqual(5);
    expect(manifest[0]!.dim).toBe(384);
    expect(manifest[0]!.bit_width).toBe(4);
  });

  it("compressed_embedding_bytes_match: f32 vec + bits=4 → committed bytes", async () => {
    for (const entry of manifest) {
      const expected = readFileSync(
        path.join(FIXTURE_DIR, `compressed_emb_seed_${entry.seed}.bin`),
      );
      const embedding = new Float32Array(entry.embedding_f32);
      const got = await compressEmbedding(embedding, entry.bit_width);
      expect(got, `seed ${entry.seed}: compress bytes`).toEqual(
        new Uint8Array(expected),
      );
    }
  });

  it("decompressed embedding round-trips back close to original", async () => {
    for (const entry of manifest) {
      const compressed = new Uint8Array(
        readFileSync(
          path.join(FIXTURE_DIR, `compressed_emb_seed_${entry.seed}.bin`),
        ),
      );
      const decomp = await decompressEmbedding(compressed, entry.dim);
      expect(decomp.length).toBe(entry.dim);
      // TurboQuant 4-bit lossy reconstruction; tolerate mean abs err < 0.5.
      let absSum = 0;
      for (let i = 0; i < decomp.length; i++) {
        absSum += Math.abs(decomp[i]! - entry.embedding_f32[i]!);
      }
      const mae = absSum / decomp.length;
      expect(mae, `seed ${entry.seed}: MAE`).toBeLessThan(0.5);
    }
  });

  it("canonical_cbor_bytes_match: artifact JSON → committed canonical bytes", async () => {
    for (const entry of manifest) {
      const expected = readFileSync(
        path.join(FIXTURE_DIR, `canonical_cbor_seed_${entry.seed}.bin`),
      );
      // Reconstruct the artifact JSON the example built. Field set must
      // match `core/examples/emit_golden.rs::build_artifact` exactly.
      const seed = entry.seed;
      const pad = String(seed).padStart(2, "0");
      const artifact = {
        artifact_id: `art:t05-seed-${seed}`,
        type: "memory",
        schema_version: 1,
        content: `T05 golden fixture seed ${seed}`,
        producer: `did:sol:${entry.signer_pubkey_b58}`,
        created_at: `2026-05-10T00:00:${pad}Z`,
        metadata: {
          embedding_compressed: entry.compressed_emb_b64,
          embed_dim: entry.dim,
          turbo_bits: entry.bit_width,
        },
      };
      const got = await toCanonicalCbor(artifact);
      expect(got, `seed ${seed}: canonical CBOR`).toEqual(
        new Uint8Array(expected),
      );
    }
  });

  it("blake3_hash matches manifest content_hash_hex", async () => {
    for (const entry of manifest) {
      const cbor = readFileSync(
        path.join(FIXTURE_DIR, `canonical_cbor_seed_${entry.seed}.bin`),
      );
      const hex = await blake3HashHex(new Uint8Array(cbor));
      expect(hex, `seed ${entry.seed}: hex hash`).toBe(entry.content_hash_hex);

      const raw = await blake3Hash(new Uint8Array(cbor));
      expect(raw.length).toBe(32);
      // Hex form of raw must equal the hex form returned by _hex.
      const rawHex = Array.from(raw)
        .map((b) => b.toString(16).padStart(2, "0"))
        .join("");
      expect(rawHex).toBe(entry.content_hash_hex);
    }
  });

  it("cose_sign1_bytes_match_server_fixture: same plaintext + same secret → byte-identical COSE", async () => {
    for (const entry of manifest) {
      const expected = readFileSync(
        path.join(FIXTURE_DIR, `cose_sign1_seed_${entry.seed}.bin`),
      );
      const cbor = new Uint8Array(
        readFileSync(
          path.join(FIXTURE_DIR, `canonical_cbor_seed_${entry.seed}.bin`),
        ),
      );
      const kp = keypairFromSecret(
        entry.signer_secret_hex,
        entry.signer_pubkey_b58,
      );
      const got = await signCosePayload(cbor, kp);
      expect(got, `seed ${entry.seed}: COSE bytes`).toEqual(
        new Uint8Array(expected),
      );
    }
  });

  // PR134-C-04: ensure the new `signAttestationBundle` export is
  // exercised. The function is the sole production signing entry
  // point in `runtime-impl.ts::signMemory` and previously had zero
  // unit-test coverage. We do not assert byte-identity here (the
  // server-side fixture set was generated against `signCosePayload` +
  // `toCanonicalCbor`, not the all-in-one bundle path) but we DO
  // assert: (1) the call resolves to a non-empty buffer; (2) the
  // first byte is 0x84 — the COSE_Sign1 marker the wrapper
  // explicitly validates.
  it("signAttestationBundle produces a non-empty COSE_Sign1-shaped envelope (PR134-C-04)", async () => {
    const entry = manifest[0];
    if (!entry) throw new Error("manifest missing");
    const embedding = new Float32Array(entry.embedding_f32);
    const compressed = await compressEmbedding(embedding, entry.bit_width);
    const contentHash = await blake3HashHex(
      new TextEncoder().encode(entry.plaintext),
    );
    const kp = keypairFromSecret(
      entry.signer_secret_hex,
      entry.signer_pubkey_b58,
    );
    const cose = await signAttestationBundle(
      entry.plaintext,
      compressed,
      contentHash,
      entry.signer_pubkey_b58,
      kp,
    );
    expect(cose.length).toBeGreaterThan(0);
    expect(cose[0]).toBe(0x84);
  });
});
