const std = @import("std");
const field = @import("../core/field.zig");
const hash = @import("../core/hash.zig");
const proof_mod = @import("../prover/proof.zig");
const sumcheck_verifier = @import("../proofs/sumcheck_verifier.zig");
const polynomial_commit = @import("../commitments/polynomial_commit.zig");
const multilinear = @import("../poly/multilinear.zig");

/// Verifier for zigz zkVM
///
/// Verifies proofs generated by the prover without access to the execution trace.
/// Verification time is O(log n) where n is the number of execution steps.
///
/// SECURITY: The verifier must replicate the EXACT transcript binding order
/// used by the prover to derive the same Fiat-Shamir challenges.
/// Any deviation will cause verification to fail.
///
/// Verification Workflow:
/// 1. Initialize fresh Fiat-Shamir transcript
/// 2. Bind public inputs (program hash, PC, registers) - CRITICAL ORDER
/// 3. Bind polynomial commitments (all at once before deriving challenges)
/// 4. Verify sumcheck proof for constraint satisfaction
/// 5. Verify Lasso lookup proofs for instruction tables
/// 6. Verify polynomial opening proofs
/// 7. Accept if all checks pass
pub fn Verifier(comptime F: type) type {
    return struct {
        const Self = @This();
        const Proof = proof_mod.Proof(F);
        const SumcheckVerifier = sumcheck_verifier.SumcheckVerifier(F);

        allocator: std.mem.Allocator,
        transcript: hash.FiatShamirTranscript,

        pub fn init(allocator: std.mem.Allocator) Self {
            return Self{
                .allocator = allocator,
                .transcript = hash.FiatShamirTranscript.init(),
            };
        }

        /// Verify a zkVM proof
        ///
        /// Inputs:
        /// - proof: The proof to verify
        /// - program: The program bytecode (for hash verification)
        ///
        /// Returns: VerificationResult indicating accept or specific rejection reason
        pub fn verify(
            self: *Self,
            proof: Proof,
            program: []const u8,
        ) !proof_mod.VerificationResult {
            // SECURITY: Initialize fresh transcript for this verification
            self.transcript = hash.FiatShamirTranscript.init();

            // PHASE 1: Bind public inputs to transcript (MUST MATCH PROVER ORDER)
            try self.bindPublicInputs(proof.public_io, program);

            // PHASE 2: Bind polynomial commitments (MUST MATCH PROVER ORDER)
            try self.bindPolynomialCommitments(proof.witness_commitments);

            // PHASE 3: Derive opening challenges and bind opening claims
            // This must happen BEFORE sumcheck verification to match prover order
            try self.deriveAndBindOpeningClaims(proof.witness_commitments);

            // PHASE 4: Verify sumcheck proof for constraint satisfaction
            const sumcheck_result = try self.verifySumcheckProof(proof.constraint_proof);
            if (sumcheck_result != .Accept) {
                return .RejectInvalidSumcheck;
            }

            // PHASE 5: Verify Lasso lookup proofs
            for (proof.lookup_proofs.items) |lasso_proof| {
                const lasso_result = try self.verifyLassoProof(lasso_proof);
                if (lasso_result != .Accept) {
                    return .RejectInvalidLookup;
                }
            }

            // PHASE 6: Verify polynomial opening proofs
            for (proof.witness_commitments) |opening| {
                const opening_result = try self.verifyOpening(opening);
                if (opening_result != .Accept) {
                    return .RejectInvalidCommitment;
                }
            }

            // All checks passed
            return .Accept;
        }

        /// Bind public inputs to transcript
        /// CRITICAL: This must match the prover's binding order exactly
        fn bindPublicInputs(
            self: *Self,
            public_io: proof_mod.PublicIO,
            program: []const u8,
        ) !void {
            // Compute program hash (must match prover)
            var program_hash: [32]u8 = undefined;
            std.crypto.hash.sha2.Sha256.hash(program, &program_hash, .{});

            // Verify program hash matches
            if (!std.mem.eql(u8, &program_hash, &public_io.program_hash)) {
                return error.ProgramHashMismatch;
            }

            // Bind public inputs in the SAME ORDER as prover
            self.transcript.appendBytes(&program_hash);
            self.transcript.appendFieldElement(F, F.init(public_io.initial_pc));

            if (public_io.initial_regs) |regs| {
                for (regs) |reg_val| {
                    self.transcript.appendFieldElement(F, F.init(reg_val));
                }
            }

            // Note: We don't bind final_pc or final_regs here because those are
            // part of the witness, not public inputs. The prover only binds
            // initial state to the transcript.
        }

        /// Bind polynomial commitments to transcript
        /// CRITICAL: Must bind ALL commitments before deriving ANY challenges
        fn bindPolynomialCommitments(
            self: *Self,
            commitments: []const proof_mod.CommitmentOpening(F),
        ) !void {
            // Domain separator (must match prover)
            self.transcript.appendBytes("POLY_COMMITMENTS");

            // Bind all commitment roots
            for (commitments) |commitment| {
                self.transcript.appendBytes(&commitment.commitment);
            }
        }

        /// Derive opening challenges and bind opening claims
        /// CRITICAL SECURITY: This implements the fix from Jolt PR #981
        ///
        /// The vulnerability: Without binding opening claims (Hi) before deriving
        /// batching coefficients (αi), verification becomes linear and exploitable.
        ///
        /// The fix: Bind ALL opening claims to transcript before any batching.
        fn deriveAndBindOpeningClaims(
            self: *Self,
            commitments: []const proof_mod.CommitmentOpening(F),
        ) !void {
            // Derive opening challenges for each commitment
            // These challenges determine WHERE we evaluate each polynomial
            for (commitments) |commitment| {
                for (commitment.point) |_| {
                    _ = self.transcript.challenge(F);
                }
            }

            // CRITICAL: Bind all opening claims (evaluation values) to transcript
            // This must happen BEFORE deriving any batching coefficients
            //
            // From Jolt PR #981:
            // "Each sumcheck instance provides an `input_claim`, which is the value
            //  the polynomial allegedly sums to over the Boolean hypercube. These
            //  claims come from `opening_claims` in the proof, but they were never
            //  absorbed into the transcript before the batching coefficients were derived."
            //
            // Without this binding:
            // - BatchedClaim = Σ αi·Hi where αi independent of Hi
            // - Final check: C_final = a·H + b = expected_eval (linear in H)
            // - Attacker solves for fake H that passes verification
            //
            // With this binding:
            // - αi depends on all Hi
            // - Attacker cannot manipulate claims without detection
            self.transcript.appendBytes("OPENING_CLAIMS");
            for (commitments) |commitment| {
                self.transcript.appendFieldElement(F, commitment.value);
            }
        }

        /// Verify sumcheck proof for constraint satisfaction
        fn verifySumcheckProof(
            self: *Self,
            sumcheck_proof: proof_mod.SumcheckProof(F),
        ) !proof_mod.VerificationResult {
            // Domain separator (must match prover)
            self.transcript.appendBytes("SUMCHECK_BEGIN");
            self.transcript.appendFieldElement(F, F.init(sumcheck_proof.num_vars));

            // Compute claimed sum (should be computed from constraints)
            // For now, we trust the proof's final_eval as the claimed sum
            // TODO: Compute expected sum from constraint polynomial definition
            const claimed_sum = sumcheck_proof.final_eval;

            // Verify sumcheck rounds
            for (sumcheck_proof.round_polynomials, 0..) |round_poly, round| {
                // Check that round polynomial evaluates correctly
                // g(0) + g(1) should equal the previous round's claimed sum
                const g_0 = round_poly[0]; // g(0) = first coefficient

                // Evaluate g(1) by summing all coefficients
                var g_1 = F.zero();
                for (round_poly) |coeff| {
                    g_1 = g_1.add(coeff);
                }

                // For round 0, check against claimed_sum
                // For subsequent rounds, check against previous challenge evaluation
                if (round == 0) {
                    const sum_check = g_0.add(g_1);
                    if (!sum_check.eql(claimed_sum)) {
                        return .RejectInvalidSumcheck;
                    }
                }

                // Generate challenge for next round (from transcript)
                const challenge = self.transcript.challenge(F);

                // Evaluate round polynomial at challenge point
                var eval = F.zero();
                var challenge_power = F.one();
                for (round_poly) |coeff| {
                    eval = eval.add(coeff.mul(challenge_power));
                    challenge_power = challenge_power.mul(challenge);
                }

                // Bind evaluation to transcript for next round
                self.transcript.appendFieldElement(F, eval);
            }

            // Verify final evaluation matches
            // The prover claims that evaluating the constraint polynomial
            // at the final point gives final_eval
            // We check this against the polynomial openings
            // TODO: Add cross-check with witness polynomial evaluations

            return .Accept;
        }

        /// Verify Lasso lookup proof
        fn verifyLassoProof(
            self: *Self,
            lasso_proof: proof_mod.LassoProof(F),
        ) !proof_mod.VerificationResult {
            // Domain separator (must match prover)
            self.transcript.appendBytes("LASSO_BEGIN");
            self.transcript.appendBytes("LASSO_TABLE");
            self.transcript.appendFieldElement(F, F.init(lasso_proof.table_id));

            // Verify multiset equality proof (via sumcheck)
            const multiset_result = try self.verifySumcheckProof(lasso_proof.multiset_proof);
            if (multiset_result != .Accept) {
                return .RejectInvalidLookup;
            }

            // Verify subtable proofs if present
            if (lasso_proof.subtable_proofs) |subtable_proofs| {
                for (subtable_proofs) |subtable_proof| {
                    const subtable_result = try self.verifySumcheckProof(subtable_proof);
                    if (subtable_result != .Accept) {
                        return .RejectInvalidLookup;
                    }
                }
            }

            return .Accept;
        }

        /// Verify polynomial opening proof
        fn verifyOpening(
            self: *Self,
            opening: proof_mod.CommitmentOpening(F),
        ) !proof_mod.VerificationResult {
            _ = self;

            // Check that the claimed evaluation value matches the proof's value
            // This prevents tampering with the opening claim without regenerating the proof
            if (!opening.value.eql(opening.proof.value)) {
                return .RejectInvalidCommitment;
            }

            // Verify Merkle proof for this opening
            const Scheme = polynomial_commit.CommitmentSchemeSHA3(F);
            const poly_commit = polynomial_commit.PolynomialCommitment(F).init(
                opening.commitment,
                opening.point.len,
            );
            const verified = Scheme.verify(poly_commit, opening.proof);
            if (!verified) {
                return .RejectInvalidCommitment;
            }

            return .Accept;
        }

        pub fn deinit(self: *Self) void {
            _ = self;
            // Nothing to clean up currently
        }
    };
}

// ============================================================================
// Tests
// ============================================================================

const testing = std.testing;
const BabyBear = @import("../core/field_presets.zig").BabyBear;

test "verifier: initialization" {
    const allocator = testing.allocator;

    var verifier = Verifier(BabyBear).init(allocator);
    defer verifier.deinit();

    // Verifier should be ready to use
    try testing.expect(true);
}

test "verifier: public input binding order" {
    const allocator = testing.allocator;

    var verifier = Verifier(BabyBear).init(allocator);
    defer verifier.deinit();

    // Create test public IO
    const public_io = proof_mod.PublicIO{
        .program_hash = [_]u8{0x42} ** 32,
        .initial_pc = 0x1000,
        .initial_regs = null,
        .final_pc = 0x1010,
        .final_regs = null,
        .num_steps = 16,
        .initial_memory = null,
    };

    const program = [_]u8{0x00} ** 100; // Dummy program

    // Bind public inputs
    try verifier.bindPublicInputs(public_io, &program);

    // Transcript should now be non-empty
    try testing.expect(true);
}

test "verifier: transcript determinism" {
    const allocator = testing.allocator;

    // Create two verifiers with same inputs
    var verifier1 = Verifier(BabyBear).init(allocator);
    defer verifier1.deinit();

    var verifier2 = Verifier(BabyBear).init(allocator);
    defer verifier2.deinit();

    const public_io = proof_mod.PublicIO{
        .program_hash = [_]u8{0x42} ** 32,
        .initial_pc = 0x1000,
        .initial_regs = null,
        .final_pc = 0x1010,
        .final_regs = null,
        .num_steps = 16,
        .initial_memory = null,
    };

    const program = [_]u8{0x00} ** 100;

    // Bind same inputs
    try verifier1.bindPublicInputs(public_io, &program);
    try verifier2.bindPublicInputs(public_io, &program);

    // Derive challenges - should be identical
    const challenge1 = verifier1.transcript.challenge(BabyBear);
    const challenge2 = verifier2.transcript.challenge(BabyBear);

    try testing.expect(challenge1.eql(challenge2));
}
