/**
 * Conformance vector integrity tests.
 *
 * These tests validate the structural and schema correctness of the
 * vectors-a2a-v1.0.0.json fixture file.  They do NOT re-execute the
 * Rust serialization pipeline (that requires the `golden-fixtures` cargo
 * feature); instead they provide fast, portable signal that the vectors
 * file is well-formed and complete enough for third-party harnesses to load.
 *
 * Byte-for-byte JCS/COSE parity checks are the responsibility of harnesses
 * that call `mnemonic-a2a` codec methods directly.
 */

import { describe, it, expect } from "vitest";
import rawVectors from "../vectors-a2a-v1.0.0.json";
import { loadVectors, vectorsForKind } from "../src/index.js";

// ── schema helpers ────────────────────────────────────────────────────────────

const HEX_RE = /^[0-9a-f]+(\.\.\.[0-9a-f]+)?$/i;

function isHexOrTruncated(s: string): boolean {
  // Vectors may contain "..." as a truncation marker in intermediate docs;
  // the actual bytes generated by the emitter are fully expanded.
  // We accept either fully-expanded hex or the truncated placeholder form.
  return HEX_RE.test(s) && s.length >= 8;
}

// ── vector count and uniqueness ───────────────────────────────────────────────

describe("vectors-a2a-v1.0.0.json", () => {
  it("has at least 22 entries", () => {
    expect(rawVectors.length).toBeGreaterThanOrEqual(22);
  });

  it("has unique names", () => {
    const names = rawVectors.map((v) => v.name);
    const unique = new Set(names);
    expect(unique.size).toBe(names.length);
  });

  it("each entry has the six required fields", () => {
    const required = [
      "name",
      "a2a_json",
      "jcs_canonical_hex",
      "cbor_envelope_hex",
      "cose_signed_hex",
      "keypair_secret_hex",
    ] as const;
    for (const v of rawVectors) {
      for (const field of required) {
        expect(
          v,
          `entry '${v.name}' is missing field '${field}'`
        ).toHaveProperty(field);
        expect(
          typeof (v as Record<string, unknown>)[field],
          `entry '${v.name}'.${field} must be a string`
        ).toBe("string");
      }
    }
  });

  it("jcs_canonical_hex is hex-like and non-trivially short", () => {
    for (const v of rawVectors) {
      expect(
        isHexOrTruncated(v.jcs_canonical_hex),
        `entry '${v.name}'.jcs_canonical_hex must be hex (got: ${v.jcs_canonical_hex.slice(0, 20)}...)`
      ).toBe(true);
    }
  });

  it("cose_signed_hex starts with COSE_Sign1 tag d284", () => {
    for (const v of rawVectors) {
      expect(
        v.cose_signed_hex.startsWith("d284"),
        `entry '${v.name}'.cose_signed_hex must start with d284 (COSE_Sign1 tag)`
      ).toBe(true);
    }
  });

  it("all entries use the same fixed keypair seed", () => {
    const FIXED_SEED = "0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20";
    // keypair_secret_hex is hex(seed ++ pubkey) = 128 hex chars, OR just the
    // seed (64 chars) in stub vectors.  Either way the string must contain the
    // fixed seed as a prefix.
    for (const v of rawVectors) {
      expect(
        v.keypair_secret_hex.startsWith(FIXED_SEED),
        `entry '${v.name}' uses a different seed than the fixed test seed`
      ).toBe(true);
    }
  });

  it("a2a_json is valid JSON for each entry", () => {
    for (const v of rawVectors) {
      expect(() => JSON.parse(v.a2a_json), `entry '${v.name}'.a2a_json is not valid JSON`).not.toThrow();
    }
  });

  // ── kind coverage ─────────────────────────────────────────────────────────

  it("covers Message, Task, and Artifact kinds", () => {
    const names = rawVectors.map((v) => v.name);
    expect(names.some((n) => n.startsWith("message_"))).toBe(true);
    expect(names.some((n) => n.startsWith("task_"))).toBe(true);
    expect(names.some((n) => n.startsWith("artifact_"))).toBe(true);
  });

  it("has at least 8 message entries", () => {
    const msgs = rawVectors.filter((v) => v.name.startsWith("message_"));
    expect(msgs.length).toBeGreaterThanOrEqual(8);
  });

  it("has at least 8 task entries", () => {
    const tasks = rawVectors.filter((v) => v.name.startsWith("task_"));
    expect(tasks.length).toBeGreaterThanOrEqual(8);
  });

  it("has at least 5 artifact entries", () => {
    const arts = rawVectors.filter((v) => v.name.startsWith("artifact_"));
    expect(arts.length).toBeGreaterThanOrEqual(5);
  });

  // ── specific fixtures ─────────────────────────────────────────────────────

  it("message_text_only has JCS-ordered keys (messageId before parts before role)", () => {
    const v = rawVectors.find((e) => e.name === "message_text_only")!;
    const obj = JSON.parse(v.a2a_json);
    const keys = Object.keys(obj);
    expect(keys.indexOf("messageId")).toBeLessThan(keys.indexOf("parts"));
    expect(keys.indexOf("parts")).toBeLessThan(keys.indexOf("role"));
  });

  it("message_utf8_cyrillic a2a_json contains Cyrillic text", () => {
    const v = rawVectors.find((e) => e.name === "message_utf8_cyrillic")!;
    expect(v.a2a_json).toMatch(/Привет/);
  });

  it("task_completed_single_artifact has artifacts array", () => {
    const v = rawVectors.find((e) => e.name === "task_completed_single_artifact")!;
    const obj = JSON.parse(v.a2a_json);
    expect(Array.isArray(obj.artifacts)).toBe(true);
    expect(obj.artifacts.length).toBeGreaterThan(0);
  });

  it("artifact_no_id has no artifactId field", () => {
    const v = rawVectors.find((e) => e.name === "artifact_no_id")!;
    const obj = JSON.parse(v.a2a_json);
    expect(obj).not.toHaveProperty("artifactId");
  });

  it("task_unknown_status preserves unknown status string", () => {
    const v = rawVectors.find((e) => e.name === "task_unknown_status")!;
    const obj = JSON.parse(v.a2a_json);
    expect(obj.status).toBe("unknown");
  });
});

// ── API surface ───────────────────────────────────────────────────────────────

describe("loadVectors()", () => {
  it("returns the same array as the raw import", () => {
    const loaded = loadVectors();
    expect(loaded).toHaveLength(rawVectors.length);
    expect(loaded[0].name).toBe(rawVectors[0].name);
  });
});

describe("vectorsForKind()", () => {
  it("filters message vectors", () => {
    const msgs = vectorsForKind("message");
    expect(msgs.length).toBeGreaterThan(0);
    for (const v of msgs) {
      expect(v.name.startsWith("message_")).toBe(true);
    }
  });

  it("filters task vectors", () => {
    const tasks = vectorsForKind("task");
    expect(tasks.length).toBeGreaterThan(0);
    for (const v of tasks) {
      expect(v.name.startsWith("task_")).toBe(true);
    }
  });

  it("filters artifact vectors", () => {
    const arts = vectorsForKind("artifact");
    expect(arts.length).toBeGreaterThan(0);
    for (const v of arts) {
      expect(v.name.startsWith("artifact_")).toBe(true);
    }
  });
});

// ── Fuzz-style structural tests (crafted A2A objects) ─────────────────────────
//
// These tests do NOT call the Rust codec. They validate that the conformance
// harness itself is resilient to vectors with edge-case JSON content — testing
// the conformance infrastructure, not the serialization pipeline.
//
// The corresponding Rust cargo-fuzz target in bridge-a2a/fuzz/ covers the
// full pipeline against arbitrary input.

describe("fuzz-style structural validation", () => {
  const REQUIRED_FIELDS = ["name", "jcs_canonical_hex", "cose_signed_hex", "keypair_secret_hex"];

  it("rejects missing required field gracefully", () => {
    const partial = { name: "fuzz_partial", jcs_canonical_hex: "deadbeef" };
    for (const field of REQUIRED_FIELDS) {
      expect(
        (partial as Record<string, unknown>)[field] !== undefined || field === "cose_signed_hex" || field === "keypair_secret_hex",
        `field '${field}' check`
      );
    }
    // Structural: confirm a harness loading this would find missing fields.
    expect(REQUIRED_FIELDS.every((f) => f in partial)).toBe(false);
  });

  it("rejects empty jcs_canonical_hex", () => {
    const empty = { name: "fuzz_empty_hex", jcs_canonical_hex: "" };
    expect(isHexOrTruncated(empty.jcs_canonical_hex)).toBe(false);
  });

  it("rejects non-JSON a2a_json", () => {
    const bad = { a2a_json: "not-json-{{{" };
    expect(() => JSON.parse(bad.a2a_json)).toThrow();
  });

  it("handles oversized cose_signed_hex (16 KB) without OOM", () => {
    const big = "d284" + "ab".repeat(8192);
    expect(big.startsWith("d284")).toBe(true);
    expect(big.length).toBe(4 + 8192 * 2);
  });

  it("handles deeply nested a2a_json without error", () => {
    let deep: unknown = "leaf";
    for (let i = 0; i < 64; i++) deep = { data: deep, kind: "data" };
    const json = JSON.stringify(deep);
    expect(() => JSON.parse(json)).not.toThrow();
  });

  it("handles unicode control characters in text parts", () => {
    const json = JSON.stringify({
      messageId: "ctrl-test",
      role: "user",
      parts: [{ kind: "text", text: " " }],
    });
    expect(() => JSON.parse(json)).not.toThrow();
  });
});
