// AUTO-GENERATED by webapp/scripts/generate-roadmap.mjs. Do not edit.
// Source: work/<feature>/{tech-spec.md,user-spec.md,tasks/*.md}
// Run `npm run roadmap` in webapp/ to regenerate.

export type RoadmapStatus = "shipped" | "in_progress" | "planned";

export interface RoadmapItem {
  id: string;
  title: string;
  description: string;
  status: RoadmapStatus;
  sourcePath: string;
}

export const ROADMAP_ITEMS: readonly RoadmapItem[] = [
  {
    "id": "docs-actualization",
    "title": "docs-actualization",
    "description": "Promote 11 evergreen documents (9 .md + 2 PDF) recovered from sivo4kin/mnemonic-protocol@docs/usecases into the public docs/ tree with surgical de-staling, expand WHITEPAPER.md §9 to cover all 10 use cases, anchor PK…",
    "status": "shipped",
    "sourcePath": "work/docs-actualization/"
  },
  {
    "id": "mnemonic-integrations",
    "title": "mnemonic-integrations Phase 1 (Hackathon MVP)",
    "description": "Ship a public mcp.mnemonik.xyz endpoint that any MCP-capable AI tool (Cursor, VS Code, Claude.ai Pro, Perplexity Pro) can install as a remote connector. Identity AND attestation signing are both client-side: the…",
    "status": "shipped",
    "sourcePath": "work/completed/mnemonic-integrations/"
  },
  {
    "id": "mnemonic-webapp",
    "title": "mnemonic-webapp (MVP Protocol Chatbot)",
    "description": "Build a React webapp backed by the existing MCP HTTP server. Add two new endpoints to the MCP server: POST /chat (RAG chatbot) and GET /download-knowledge (pre-built artifact). Add a startup seeding routine that…",
    "status": "shipped",
    "sourcePath": "work/mnemonic-webapp/"
  },
  {
    "id": "mnemonic-cli",
    "title": "mnemonic-cli (Phase 1 — SDK + CLI)",
    "description": "Ship two pure-ESM npm packages under the @mnemonik-xyz scope:",
    "status": "in_progress",
    "sourcePath": "work/mnemonic-cli/"
  },
  {
    "id": "mnemonic-core",
    "title": "mnemonic-core extraction",
    "description": "Extract all domain logic from the monolithic MCP server (mnemonic-protocol/mcp/) into a standalone Rust library crate mnemonic-core. The MCP server becomes a thin wrapper that depends on core as a Cargo workspace member.",
    "status": "in_progress",
    "sourcePath": "work/mnemonic-core/"
  },
  {
    "id": "a2a-bridge",
    "title": "A2A Bridge",
    "description": "Three layers, deployable independently:",
    "status": "planned",
    "sourcePath": "work/a2a-bridge/"
  },
  {
    "id": "cursor-vscode-e2e-tests",
    "title": "Cursor / VS Code / Claude Desktop E2E test coverage",
    "description": "Three tiers, by determinism + cost:",
    "status": "planned",
    "sourcePath": "work/cursor-vscode-e2e-tests/"
  },
  {
    "id": "keypair-sync",
    "title": "Keypair Sync — eliminate localStorage ↔ identity.json drift",
    "description": "Multi-tenant keypairs (a single user with one CLI + multiple browsers would need a different design — out of scope until we have the use case). Migrating existing local: synthetic-tx attestations to a new keypair…",
    "status": "planned",
    "sourcePath": "work/keypair-sync/"
  }
] as const;
